spring.application.name=ems-project

spring.datasource.url=jdbc:mysql://localhost:3306/emss
spring.datasource.username=root
spring.datasource.password=Devashri

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect